---
apiVersion: v2
appVersion: 0.0.1
description: An nut information exporter to influxdb 2 runner
name: nut-influxdb-exporter
version: 0.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - nut-influxdb-exporter
home: https://github.com/mwinters-stuff/nut-influxdb-exporter
sources:
  - https://github.com/mwinters-stuff/nut-influxdb-exporter
maintainers:
  - name: mwinters
    email: mathew@winters.nz
dependencies:
  - name: common
    repository: oci://harbor.winters.org.nz/k8s-at-winters
    version: 0.1.5
