name: Create docker image

on:
  repository_dispatch:
    types: [start-build]
  workflow_dispatch:

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup Helm
      uses: ./.github/actions/helm
      with:
        version: 3.9.0

    - name: Bump version and push tag
      id: version
      uses: hennejg/github-tag-action@v4.3.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1


    
    - name: version-print
      run: echo "Version ${{steps.version.outputs.new_version}}"
    
    - id: modify
      name: Modify scripts and get version
      run: ./build.sh main

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./nut-influxdb-exporter
        file: ./nut-influxdb-exporter/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/${{github.repository}}:latest
          ghcr.io/${{github.repository}}:${{steps.version.outputs.new_version}}

    - name: Publish Helm chart to GHCR
      run: |
          helm repo add k8s-at-home https://library-charts.k8s-at-home.com
          helm dependency build charts/nut-influxdb-exporter
          helm package charts/nut-influxdb-exporter --version ${{ steps.version.outputs.new_version }}
          helm repo index .
          git config --global user.email "mathew@winters.org.nz"
          git config --global user.name "Automated Build"
          git add -f nut-influxdb-exporter-${{ steps.version.outputs.new_version }}.tgz
          git add -f index.yaml
          git commit -m "helm chart version ${{ steps.version.outputs.new_version }}"
          git push
