name: Build and Publish

on:
  workflow_dispatch:
  repository_dispatch:
    types: [start-build]
  

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Bump version and push tag
      id: version
      uses: hennejg/github-tag-action@v4.3.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: harbor.local.winters.nz
        username: robot$github
        password: ${{ secrets.HARBOR }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./docker/
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          harbor.local.winters.nz/library/nut-influxdb-exporter:latest
          harbor.local.winters.nz/library/nut-influxdb-exporter:${{steps.version.outputs.new_version}}

    - name: Chart version
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.version = "${{steps.version.outputs.new_version}}" | .appVersion = "${{steps.version.outputs.new_version}}"' 'charts/nut-influxdb-exporter/Chart.yaml'

    - name: Get helm dependancies
      run: |
          helm repo add k8s-at-home https://library-charts.k8s-at-home.com
          helm dependency build charts/nut-influxdb-exporter
    
    - name: Push Helm Chart to ChartMuseum
      uses: bsord/helm-push@v4
      with:
        username: robot$github
        password: ${{ secrets.HARBOR }}
        registry-url: 'https://harbor.local.winters.nz/chartrepo/library'
        force: true
        chart-folder: charts/nut-influxdb-exporter
